import type { Metadata } from "next";
import { Barriecito } from "next/font/google";
import "./globals.css";


const barriecito = Barriecito({
  weight: "400",
  variable: "--font-barriecito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barriecito.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
